"""partial index for faculty contract price

Revision ID: 4a34425cc126
Revises: d0634d1d8108
Create Date: 2024-05-17 12:10:05.718641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4a34425cc126"
down_revision: Union[str, None] = "d0634d1d8108"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_unique_active_faculty_id",
        "faculty_contract_prices",
        ["faculty_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_unique_active_faculty_id",
        table_name="faculty_contract_prices",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
