"""ix for paymentss

Revision ID: 7c785fef0664
Revises: eb17af85ba87
Create Date: 2024-05-21 16:01:46.243200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c785fef0664'
down_revision: Union[str, None] = 'eb17af85ba87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_passport_number_key', 'payments', type_='unique')
    op.create_index('ix_unique_contract_number_passport_number', 'payments', ['contract_number', 'passport_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_contract_number_passport_number', table_name='payments')
    op.create_unique_constraint('payments_passport_number_key', 'payments', ['passport_number'])
    # ### end Alembic commands ###
