"""updated_uniq_constraints_con_temps

Revision ID: 9714e58fb9c2
Revises: 092e0afa6aee
Create Date: 2024-04-18 16:38:36.139735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9714e58fb9c2"
down_revision: Union[str, None] = "092e0afa6aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_templates", sa.Column("deleted_by", sa.Uuid(), nullable=True)
    )
    op.drop_constraint(
        "unique_branch_degree_active_constraint",
        "contract_templates",
        type_="unique",
    )
    op.create_unique_constraint(
        "unique_branch_degree_deleted_constraint",
        "contract_templates",
        ["branch_id", "degree_program", "language", "deleted_at"],
    )
    op.add_column(
        "faculty_contract_prices",
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faculty_contract_prices", "deleted_by")
    op.drop_constraint(
        "unique_branch_degree_deleted_constraint",
        "contract_templates",
        type_="unique",
    )
    op.create_unique_constraint(
        "unique_branch_degree_active_constraint",
        "contract_templates",
        ["branch_id", "degree_program", "language", "is_active"],
    )
    op.drop_column("contract_templates", "deleted_by")
    # ### end Alembic commands ###
