"""indexable contracts

Revision ID: f1249ab0d572
Revises: 7ef5e343424f
Create Date: 2024-05-13 15:42:49.717116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f1249ab0d572"
down_revision: Union[str, None] = "7ef5e343424f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_branch_degree_deleted_constraint", "contract_templates", type_="unique"
    )
    op.create_index(
        "ix_active_contracts",
        "contract_templates",
        ["branch_id", "degree_program", "language"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_active_contracts",
        table_name="contract_templates",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        "unique_branch_degree_deleted_constraint",
        "contract_templates",
        ["branch_id", "degree_program", "language", "deleted_at"],
    )
    # ### end Alembic commands ###
