"""added unique property for columns in faculty contract price and students counter

Revision ID: fa0b05ee8ff7
Revises: f1249ab0d572
Create Date: 2024-05-14 13:26:36.768867

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fa0b05ee8ff7"
down_revision: Union[str, None] = "f1249ab0d572"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "faculty_contract_prices", ["faculty_id"])
    op.create_unique_constraint(None, "faculty_students_counter", ["faculty_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "faculty_students_counter", type_="unique")
    op.drop_constraint(None, "faculty_contract_prices", type_="unique")
    # ### end Alembic commands ###
